### PR TITLE
Use the new Travis Docker infrastructure and stuff

### PR DESCRIPTION
**Pull request by sethvargo**

### CODE REVIEW

**Comment by sethvargo** [comment]
@ryanuber any idea why this is failing?

**Comment by ryanuber** [comment]
@sethvargo it looks like maybe something on Travis changed. The `setup_test_subnet` script brings up a bunch of IP's on 127.0.0.x to run the tests, but this used to only be required on Mac. It doesn't look like the script has changed since forever ago, so the only thing I can think of is that the IP's were previously routable on Travis, and now they are not.

**Comment by ryanuber** [comment]
Oh, or if this is now building in docker, that could very well be the cause.

**Comment by sethvargo** [comment]
Ah yea. This is running in Travis' new Docker. Let me try disabling that.

**Comment by ryanuber** [comment]
@sethvargo it looks like we made it past the networking thing after your changes. I just pushed to master to fix another bug, so if you rebase this the tests **should** start passing again.

**Comment by sethvargo** [comment]
@ryanuber it still seems to be failing

**Comment by ryanuber** [comment]
@sethvargo earlier you had removed `sudo: false`. I think we still need that since the network scenario in Docker won't allow our tests to run.

**Comment by sethvargo** [comment]
Okay. Trying again.

**Comment by sethvargo** [comment]
@ryanuber okay, idk what's going on here... I'm just going to close this out and maybe revisit it another day.

**Pull request closed without merging**
